name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: |
          npm test
          if [ $? -ne 0 ]; then
            echo "Tests failed. Please check the test logs."
          fi
        continue-on-error: true

      - name: Run linting
        run: |
          npm run lint
          if [ $? -ne 0 ]; then
            echo "Linting failed. Please check the linting logs."
          fi
        continue-on-error: true
