name: Generate Release Notes

on:
  push:
    branches:
      - main

jobs:
  generate_release_notes:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Generate Release Notes
        run: |
          # Run a script to generate release notes
          npm run generate-release-notes > release_notes.txt
          cat release_notes.txt
