name: Dependency Updates

on:
  schedule:
    - cron: '0 3 * * *' 

jobs:
  dependency_updates:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run dependency updates
        run: npm update

      - name: Run tests
        run: npm test
        continue-on-error: true

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m "chore: Update dependencies"
          git push

